export const productContants = {
  PRODUCT_FORM_SET_JSON: "PRODUCT_FORM_SET_JSON",
  GET_ALL_PRODUCT_REQUEST: "GET_ALL_PRODUCT_REQUEST",
  GET_ALL_PRODUCT_FAILURE: "GET_ALL_PRODUCT_FAILURE",
  GET_ALL_PRODUCT_SUCCESS: "GET_ALL_PRODUCT_SUCCESS",
  GET_PRODUCT_REQUEST: "GET_PRODUCT_REQUEST",
  GET_PRODUCT_FAILURE: "GET_PRODUCT_FAILURE",
  GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
  GET_CART_REQUEST: "GET_CART_REQUEST",
  GET_CART_FAILURE: "GET_CART_FAILURE",
  GET_CART_SUCCESS: "GET_CART_SUCCESS",
};
export const permissionContants = {
  PRODUCT_FORM_SET_JSON: "PRODUCT_FORM_SET_JSON",
  GET_ALL_ROLE_REQUEST: "GET_ALL_ROLE_REQUEST",
  GET_ALL_ROLE_FAILURE: "GET_ALL_ROLE_FAILURE",
  GET_ALL_ROLE_SUCCESS: "GET_ALL_ROLE_SUCCESS",
  GET_ROLE_REQUEST: "GET_ROLE_REQUEST",
  GET_ROLE_FAILURE: "GET_ROLE_FAILURE",
  GET_ROLE_SUCCESS: "GET_ROLE_SUCCESS",
  GET_PERMISSION_MENU_REQUEST: "GET_PERMISSION_MENU_REQUEST",
  GET_PERMISSION_MENU_FAILURE: "GET_PERMISSION_MENU_FAILURE",
  GET_PERMISSION_MENU_SUCCESS: "GET_PERMISSION_MENU_SUCCESS",
};

export const userContants = {
  USER_ROLE_ASSIGN_SET_JSON: "USER_ROLE_ASSIGN_SET_JSON",
  GET_USER__REQUEST: "GET_USER__REQUEST",
  GET_USER__SUCCESS: "GET_USER__SUCCESS",
  SET_UPDATED_ROLE: "SET_UPDATED_ROLE",
  EMAIL_CHECKER_REQUEST: "EMAIL_CHECKER_REQUEST",
  EMAIL_CHECKER_FAILURE: "EMAIL_CHECKER_FAILURE",
  EMAIL_CHECKER_SUCCESS: "EMAIL_CHECKER_SUCCESS",
  CHECK_USER_STATUS_REQUEST: "CHECK_USER_STATUS_REQUEST",
  CHECK_USER_STATUS_SUCCESS: "CHECK_USER_STATUS_SUCCESS",
  CHECK_USER_STATUS_FAILURE: "CHECK_USER_STATUS_FAILURE",
  UPDATE_STATE_REQUEST: "UPDATE_STATE_REQUEST",
  UPDATE_STATE_SUCCESS: "UPDATE_STATE_SUCCESS",
  USER_UPDATE_REQUEST: "USER_UPDATE_REQUEST",
  USER_UPDATE_SUCCESS: "USER_UPDATE_SUCCESS",
};

export const dynaamicTableConst = {
  CHECKBOX_DEFAULT_VALUE_SET: "CHECKBOX_DEFAULT_VALUE_SET",
  CHECKBOX_VALUE_SET_ON_INDEX: "CHECKBOX_VALUE_SET_ON_INDEX",
};
