export const productContants = {
  PRODUCT_FORM_SET_JSON: "PRODUCT_FORM_SET_JSON",
  GET_ALL_PRODUCT_REQUEST: "GET_ALL_PRODUCT_REQUEST",
  GET_ALL_PRODUCT_FAILURE: "GET_ALL_PRODUCT_FAILURE",
  GET_ALL_PRODUCT_SUCCESS: "GET_ALL_PRODUCT_SUCCESS",

  GET_PRODUCT_REQUEST: "GET_PRODUCT_REQUEST",
  GET_PRODUCT_FAILURE: "GET_PRODUCT_FAILURE",
  GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",

  RESET_STATE: "RESET_STATE",
};

export const userContants = {
  USER_ROLE_ASSIGN_SET_JSON: "USER_ROLE_ASSIGN_SET_JSON",
  GET_USER__REQUEST: "GET_USER__REQUEST",
  GET_USER__SUCCESS: "GET_USER__SUCCESS",
  SET_UPDATED_ROLE: "SET_UPDATED_ROLE",

  RESET_USER_MESSAGE: "RESET_USER_MESSAGE",
  EMAIL_CHECKER_REQUEST: "EMAIL_CHECKER_REQUEST",
  EMAIL_CHECKER_FAILURE: "EMAIL_CHECKER_FAILURE",
  EMAIL_CHECKER_SUCCESS: "EMAIL_CHECKER_SUCCESS",

  CHECK_USER_STATUS_REQUEST: "CHECK_USER_STATUS_REQUEST",
  CHECK_USER_STATUS_SUCCESS: "CHECK_USER_STATUS_SUCCESS",
  CHECK_USER_STATUS_FAILURE: "CHECK_USER_STATUS_FAILURE",

  UPDATE_STATE_REQUEST: "UPDATE_STATE_REQUEST",
  UPDATE_STATE_SUCCESS: "UPDATE_STATE_SUCCESS",

  USER_UPDATE_REQUEST: "USER_UPDATE_REQUEST",
  USER_UPDATE_SUCCESS: "USER_UPDATE_SUCCESS",

  USER_IS_PRESENT_OR_NOT_REQUEST: "USER_IS_PRESENT_OR_NOT_REQUEST",
  USER_IS_PRESENT_OR_NOT_SUCCESS: "USER_IS_PRESENT_OR_NOT_SUCCESS",
  ADD_USER_REQUEST: "ADD_USER_REQUEST",
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  ADD_USER_FAILURE: "ADD_USER_FAILURE",
  GET_USER_PROFILE_REQUEST: "GET_USER_PROFILE_REQUEST",
  GET_USER_PROFILE_SUCCESS: "GET_USER_PROFILE_SUCCESS",
  GET_USER_PROFILE_FAILURE: "GET_USER_PROFILE_FAILURE",

  UPDATE_PAYMENT_STATUS_REQUEST: "UPDATE_PAYMENT_STATUS_REQUEST",
  UPDATE_PAYMENT_STATUS_SUCCESS: "UPDATE_PAYMENT_STATUS_SUCCESS",
  UPDATE_PAYMENT_STATUS_FAILURE: "UPDATE_PAYMENT_STATUS_FAILURE",

  RESET_USER_STATUS: "RESET_USER_STATUS",
};
